TNSMI = {
    CARDAREAS = {},
    row = 2,
    card_per_row = 6,
    page = 1,
    pagecounter = 0,
    prompt_text_input = "",
    menu_mod = "base",
    mod_config = SMODS.current_mod.config,
    filterpacks = {}
}
SMODS.Atlas{key = "modicon", path = "modicon.png", px = 32, py = 32}

local mod_contents = {
	"utils",
    "overrides",
    "callbacks",
    "UI",
}
for k, v in pairs(mod_contents) do
	assert(SMODS.load_file('/src/'..v..'.lua'))()
end
TNSMI.Pack{
    name = "Fool's Gambit",
    description = {
        {
            lan = 'en-us',
            text = {
                "This is the SFX Used in",
                "Fool's Gambit."
            },
        },
    },
    mods = {"Vanilla"},
    authors = {"GoldenLeaf"},
    thumbnail = "thumb",
    sound_table = {
        { key = "hehehe", prefix = "adgeda_"},
        { key = "ambientFire1", },
        { key = "ambientFire2" },
        { key = "ambientFire3" },
        { key = "ambientOrgan1" },
        { key = "button" },
        { key = "cancel" },
        { key = "card1" },
        { key = "card3" },
        { key = "cardFan2" },
        { key = "cardSlide1" },
        { key = "cardSlide2" },
        { key = "chips1" },
        { key = "chips2" },
        { key = "coin1" },
        { key = "coin2" },
        { key = "coin3" },
        { key = "coin4" },
        { key = "coin5" },
        { key = "coin6" },
        { key = "coin7" },
        { key = "crumple1" },
        { key = "crumple2" },
        { key = "crumple3" },
        { key = "crumple4" },
        { key = "crumple5" },
        { key = "crumpleLong1" },
        { key = "crumpleLong2" },
        { key = "explosion_buildup1" },
        { key = "explosion_release1" },
        { key = "explosion1" },
        { key = "foil1" },
        { key = "foil2" },
        { key = "generic1" },
        { key = "glass1" },
        { key = "glass2" },
        { key = "glass3" },
        { key = "glass4" },
        { key = "glass5" },
        { key = "glass6" },
        { key = "gold_seal" },
        { key = "gong" },
        { key = "highlight1" },
        { key = "highlight2" },
        { key = "holo1" },
        { key = "introPad1" },
        { key = "magic_crumple" },
        { key = "magic_crumple2" },
        { key = "magic_crumple3" },
        { key = "multhit1" },
        { key = "multhit2" },
        { key = "negative" },
        { key = "other1" },
        { key = "paper1" },
        { key = "polychrome1" },
        { key = "slice1" },
        { key = "splash_buildup" },
        { key = "tarot1" },
        { key = "tarot2" },
        { key = "timpani" },
        { key = "voice1" },
        { key = "voice2" },
        { key = "voice3" },
        { key = "voice4" },
        { key = "voice5" },
        { key = "voice6" },
        { key = "voice7" },
        { key = "voice8" },
        { key = "voice9" },
        { key = "voice10" },
        { key = "voice11" },
        { key = "whoosh_long" },
        { key = "whoosh" },
        { key = "whoosh1" },
        { key = "whoosh2" },
        { key = "win" }
    },
}