TNSMI = SMODS.current_mod
TNSMI.cardareas = {}
TNSMI.pages = {current = 1, num = 1}
TNSMI.prompt_text_input = ''
SMODS.Atlas{key = "modicon", path = "modicon.png", px = 32, py = 32}

local mod_contents = {
	"utils",
    "overrides",
    "callbacks",
    "UI",
}
for k, v in pairs(mod_contents) do
	assert(SMODS.load_file('/src/'..v..'.lua'))()
end

TNSMI.MusicPack({
    key = 'fools_gambit',
    sounds = {
        { replace_key = "ambientFire1" },
        { replace_key = "ambientFire2"  },
        { replace_key = "ambientFire3"  },
        { replace_key = "ambientOrgan1"  },
        { replace_key = "button"  },
        { replace_key = "cancel"  },
        { replace_key = "card1"  },
        { replace_key = "card3"  },
        { replace_key = "cardFan2"  },
        { replace_key = "cardSlide1"  },
        { replace_key = "cardSlide2"  },
        { replace_key = "chips1"  },
        { replace_key = "chips2"  },
        { replace_key = "coin1"  },
        { replace_key = "coin2"  },
        { replace_key = "coin3"  },
        { replace_key = "coin4"  },
        { replace_key = "coin5"  },
        { replace_key = "coin6"  },
        { replace_key = "coin7"  },
        { replace_key = "crumple1"  },
        { replace_key = "crumple2"  },
        { replace_key = "crumple3"  },
        { replace_key = "crumple4"  },
        { replace_key = "crumple5"  },
        { replace_key = "crumpleLong1"  },
        { replace_key = "crumpleLong2"  },
        { replace_key = "explosion_buildup1"  },
        { replace_key = "explosion_release1"  },
        { replace_key = "explosion1"  },
        { replace_key = "foil1"  },
        { replace_key = "foil2"  },
        { replace_key = "generic1"  },
        { replace_key = "glass1"  },
        { replace_key = "glass2"  },
        { replace_key = "glass3"  },
        { replace_key = "glass4"  },
        { replace_key = "glass5"  },
        { replace_key = "glass6"  },
        { replace_key = "gold_seal"  },
        { replace_key = "gong"  },
        { replace_key = "highlight1"  },
        { replace_key = "highlight2"  },
        { replace_key = "holo1"  },
        { replace_key = "introPad1"  },
        { replace_key = "magic_crumple"  },
        { replace_key = "magic_crumple2"  },
        { replace_key = "magic_crumple3"  },
        { replace_key = "multhit1"  },
        { replace_key = "multhit2"  },
        { replace_key = "negative"  },
        { replace_key = "other1"  },
        { replace_key = "paper1"  },
        { replace_key = "polychrome1"  },
        { replace_key = "slice1"  },
        { replace_key = "splash_buildup"  },
        { replace_key = "tarot1"  },
        { replace_key = "tarot2"  },
        { replace_key = "timpani"  },
        { replace_key = "voice1"  },
        { replace_key = "voice2"  },
        { replace_key = "voice3"  },
        { replace_key = "voice4"  },
        { replace_key = "voice5"  },
        { replace_key = "voice6"  },
        { replace_key = "voice7" },
        { replace_key = "voice8" },
        { replace_key = "voice9" },
        { replace_key = "voice10" },
        { replace_key = "voice11" },
        { replace_key = "whoosh_long" },
        { replace_key = "whoosh" },
        { replace_key = "whoosh1" },
        { replace_key = "whoosh2" },
        { replace_key = "win" },
        { replace_key = "music1", path = 'main.ogg', pitch = 1},
        { replace_key = "music2", path = 'arcana.ogg', pitch = 1},
        { replace_key = "music3", path = 'celestial.ogg', pitch = 1},
        { replace_key = "music4", path = 'shop.ogg', pitch = 1},
        { replace_key = "music5", path = 'boss.ogg', pitch = 1}
    },
})